name: skate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - compilers
  - python-casacore
  - boost
  - pip
  - pip:
    - --index-url=https://artefact.skao.int/repository/pypi-all/simple
    - rascil
    - --extra-index-url https://artefact.skao.int/repository/pypi-internal/simpl
    - ska-ost-array-config
    - typing-extensions
    - marshmallow
    - numba
    - -e .
